Tidy up Makefile

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -1,12 +1,22 @@
-LIBTI99DIR?=/home/mark/ti99/libti99
-
+##
+#  Directories where tools are located.  Edit to reflect your setup
+##
+LIBTI99DIR?=~/work/ti99/libTi99All/buildti
 # GCCDIR=/opt/tms9900-gcc/bin/
 GCCDIR=../gcc4/bin/
 
+##
+#  Locations of tools relative to directories defined above
+##
 GAS=$(GCCDIR)tms9900-as
 LD=$(GCCDIR)tms9900-ld
 CC=$(GCCDIR)tms9900-gcc
 LIBGCC=$(GCCDIR)../lib/gcc/tms9900/4.4.0/libgcc.a
+CRT0=$(LIBTI99DIR)/crt0_ea5.o
+
+##
+# Define test targets
+##
 
 # Tests are split up so as to fit into an 8K bin file
 # to make a cartridge bin.  Note some tests will not fit into a cartridge
@@ -25,39 +35,28 @@ test_subreg \
 test_array
 
 BINTARGETS=$(TARGETS:=.bin)
+ELFTARGETS=$(TARGETS:=.elf)
 
-all: $(BINTARGETS) harness/harness
+.PHONY: test clean harness
+all: $(BINTARGETS) harness
 
-.PHONY: test clean harness/harness
-
-harness/harness:
-	$(MAKE) -C harness
-
-test: $(BINTARGETS) harness/harness
-	@for target in $(BINTARGETS); do \
-            harness/harness -f $$target ; \
-            count=$$(($$count + $$?)) ; \
-        done ; \
-	if [ $$count -gt 0 ]; then \
-	echo "\n*** $$count tests FAILED\n" ; \
-	else \
-	echo "\n*** all tests passed\n" ; \
-	fi
-
+##
+#  Define make flags
+##
 ifdef EA5
 ELF2BIN=../elfutils/elf2ea5
 LDFLAGS=--section-start .text=a000 --section-start .data=2080 -M
-FNAME=test.ea5
 else
 ELF2BIN=../elfutils/elf2cart
 LDFLAGS=--section-start .text=6000 --section-start .data=2080
 HEADER=header.o
-FNAME=test.bin
 endif
+
+OBJECTS=tap.o params.o
 
 CFLAGS=-std=c99 --save-temp -I$(LIBTI99DIR)
 
-#  test with and without -O2.
+#  All tests should be run with and without -O2 and -Os for complete coverage
 #
 #  NOTE some tests are useless with -O2 as the compiler optimises away any
 #  arithmetic or comparisons with constants.
@@ -73,13 +72,24 @@ CFLAGS=-std=c99 --save-temp -I$(LIBTI99DIR)
 # Uncomment to build binary for use with emulator
 CFLAGS+=-DEMUL_TEST=1
 
-HEADER+=$(LIBTI99DIR)/crt0_ea5.o
-
 LIBTI99=-lti99
 
-# OBJECT_LIST=temu_hdr.o
+##
+#  Define make rules
+##
+harness:
+	$(MAKE) -C harness
 
-OBJECTS=tap.o params.o
+test: $(BINTARGETS) harness
+	@for target in $(BINTARGETS); do \
+            harness/harness -f $$target ; \
+            count=$$(($$count + $$?)) ; \
+        done ; \
+	if [ $$count -gt 0 ]; then \
+	echo "\n*** $$count tests FAILED\n" ; \
+	else \
+	echo "\n*** all tests passed\n" ; \
+	fi
 
 #  Build on host.  Used to verify tests
 host-test: test.c
@@ -95,8 +105,8 @@ $(BINTARGETS): %.bin: %.elf
 #  NOTE link order is important.  Headers must be first and target can't be last.  There is some issue with byte
 #  alignment if target is last.
 
-%.elf: %.o $(HEADER) $(OBJECTS)
-	$(LD) $(HEADER) $< $(OBJECTS) -o $@ $(LDFLAGS) -L$(LIBTI99DIR) $(LIBTI99) \
+$(ELFTARGETS): %.elf: %.o $(OBJECTS) $(HEADER)
+	$(LD) $(HEADER) $(CRT0) $< $(OBJECTS) -o $@ $(LDFLAGS) -L $(LIBTI99DIR) $(LIBTI99) \
 	-Map=$(patsubst %.elf,%.map,$@) $(LIBGCC)
 
 clean:
