1.32 (#67)
* Fixed left and right shifts by a byte variable
* Add extra check for zero to rotate by register and removed word alignment of byte constants
* Fixed problems with subtract word and byte (rsubihi insn)
* Refactored shift insns to take subregs properly into account
* Add andhi to shifts to fix int32 unit tests
* Added fix to rsubihi problem with label refs
* Fixed 32-bit integer initialisation
* Removed cmphi-movhi peephole
* Added test harness with emulated CPU and XOP 15 for traps
* Ensured all unit tests pass with and without optimisation
* Fixed unrecognised insn in initialisation of longs
* Disabled cmphi peephole and add fallthrough to binutils code
* Refactored movsi to not do highpart/lowpart on regs
* Add reg mov thru r0 to fix off-by-one-bug in byte sub
* Use short instead of int16_t for compatibility with mingw32
* Update repo scripts for multi-distro
* Fix harness options for r-pi

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -1,41 +1,62 @@
-LIBTI99DIR?=../libti99
+##
+#  Directories where tools are located.  Edit to reflect your setup
+##
+LIBTI99DIR?=~/work/ti99/libTi99All/buildti
+# GCCDIR=/opt/tms9900-gcc/bin/
+GCCDIR=../gcc4/bin/
 
-GCCDIR=/opt/tms9900-gcc/bin/
-
+##
+#  Locations of tools relative to directories defined above
+##
 GAS=$(GCCDIR)tms9900-as
 LD=$(GCCDIR)tms9900-ld
 CC=$(GCCDIR)tms9900-gcc
 LIBGCC=$(GCCDIR)../lib/gcc/tms9900/4.4.0/libgcc.a
+CRT0=$(LIBTI99DIR)/crt0_ea5.o
 
-# Uncomment one test file here.  Tests are split up so as to fit into an 8K bin file
+##
+# Define test targets
+##
+
+# Tests are split up so as to fit into an 8K bin file
 # to make a cartridge bin.  Note some tests will not fit into a cartridge
 # without optimisation.  Check the bin file is less than 8192 bytes before
 # running.
 
-# TODO make these targets
+# test_float is not tested by this framework as it uses the console ROM
+# floating point routines
+NONTARGET=test_float
 
-# TEST_SRC=test_char_short
-TEST_SRC=test_long
-# TEST_SRC=test_float
-# TEST_SRC=test_misc
-# TEST_SRC=test_subreg
-# TEST_SRC=test_one
-# TEST_SRC=zap
+TARGETS=\
+test_char_short \
+test_long \
+test_misc \
+test_subreg \
+test_array
 
+BINTARGETS=$(TARGETS:=.bin)
+ELFTARGETS=$(TARGETS:=.elf)
+
+.PHONY: test clean harness
+all: $(BINTARGETS) harness
+
+##
+#  Define make flags
+##
 ifdef EA5
-ELF2BIN=../utils/elf2ea5
+ELF2BIN=../elfutils/elf2ea5
 LDFLAGS=--section-start .text=a000 --section-start .data=2080 -M
-FNAME=test.ea5
 else
-ELF2BIN=../utils/elf2cart
+ELF2BIN=../elfutils/elf2cart
 LDFLAGS=--section-start .text=6000 --section-start .data=2080
-OBJECT_LIST=header.o
-FNAME=test.bin
+HEADER=header.o
 endif
+
+OBJECTS=tap.o params.o
 
 CFLAGS=-std=c99 --save-temp -I$(LIBTI99DIR)
 
-#  test with and without -O2.
+#  All tests should be run with and without -O2 and -Os for complete coverage
 #
 #  NOTE some tests are useless with -O2 as the compiler optimises away any
 #  arithmetic or comparisons with constants.
@@ -49,20 +70,26 @@ CFLAGS=-std=c99 --save-temp -I$(LIBTI99DIR)
 # CFLAGS+=-D_DEBUG=1
 
 # Uncomment to build binary for use with emulator
-# CFLAGS+=-DEMUL_TEST=1
-
-CRT0 = $(LIBTI99DIR)/crt0_ea5.o
+CFLAGS+=-DEMUL_TEST=1
 
 LIBTI99=-lti99
 
-# OBJECT_LIST=temu_hdr.o
+##
+#  Define make rules
+##
+harness:
+	$(MAKE) -C harness
 
-OBJECT_LIST+=\
-  $(CRT0)\
-  $(TEST_SRC).o \
-  tap.o
-
-all: $(FNAME)
+test: $(BINTARGETS) harness
+	@for target in $(BINTARGETS); do \
+            harness/harness -f $$target ; \
+            count=$$(($$count + $$?)) ; \
+        done ; \
+	if [ $$count -gt 0 ]; then \
+	echo "\n*** $$count tests FAILED\n" ; \
+	else \
+	echo "\n*** all tests passed\n" ; \
+	fi
 
 #  Build on host.  Used to verify tests
 host-test: test.c
@@ -72,19 +99,23 @@ host-test: test.c
 #	size=$(wc -c < $(FNAME).bin)
 #        if (size > 8191) $(error
 
-$(FNAME): $(FNAME).elf
-	$(ELF2BIN) $(FNAME).elf $(FNAME)
+$(BINTARGETS): %.bin: %.elf
+	$(ELF2BIN) $< $@
 
-$(FNAME).elf: $(OBJECT_LIST)
-	$(LD) $(OBJECT_LIST) $(LDFLAGS) -L$(LIBTI99DIR) $(LIBTI99) -o $(FNAME).elf \
-	-Map=mapfile $(LIBGCC)
+#  NOTE link order is important.  Headers must be first and target can't be last.  There is some issue with byte
+#  alignment if target is last.
 
-.phony clean:
+$(ELFTARGETS): %.elf: %.o $(OBJECTS) $(HEADER)
+	$(LD) $(HEADER) $(CRT0) $< $(OBJECTS) -o $@ $(LDFLAGS) -L $(LIBTI99DIR) $(LIBTI99) \
+	-Map=$(patsubst %.elf,%.map,$@) $(LIBGCC)
+
+clean:
 	rm -f *.o
 	rm -f *.elf
 	rm -f *.bin
 	rm -f *.i
 	rm -f *.s
+	rm -f *.map
 	rm -f mapfile
 	rm -f gccdump.*
 	rm -f *.c.*r.*
